{
    "cmd": ["coffee", "${debug?--nodejs}", "${debug?--nocrankshaft --nolazy --nodead_code_elimination --debug-brk=15454}", "$file", "$args"],
    "debugger": "v8",
    "debugport": 15454,
    "selector": "source.coffee",
    "info": "Your code is running at \\033[01;34m$url\\033[00m.\n\\033[01;31mImportant:\\033[00m use \\033[01;32mprocess.env.PORT\\033[00m as the port and \\033[01;32mprocess.env.IP\\033[00m as the host in your scripts!\n"
}