{
    "cmd": [
        "php",
        "${debug?-d}", "${debug?xdebug.remote_enable=1}",
        "-S", "$ip:$port"
    ],
    "selector": "^.*\\.(php)$",
    "working_dir": "$project_path",
    "debugger": "xdebug",
    "debugport": 9000,
    "env": {
        "XDEBUG_CONFIG": "idekey=cloud9ide remote_host=localhost remote_port=9000 remote_mode=req"
    },
    "info": "Starting PHP built-in web server, serving \\033[01;34m$hostname_path\\033[00m."
}